AllCops:
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
  NewCops: enable
  TargetRubyVersion: 3.2.x
Metrics/BlockLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'
Layout/LineLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'
